### ISSUE TITLE
How would I run this on Openshift.com

### ISSUE THREAD

**Issue by ryannix123** [nginxinc/docker-nginx-openshift#3]
Hello,

Do I need to use Kompose.io to run this as a container in an Openshift project?

Thanks,

Ryan

**Comment by alessfg** [comment]
Hi @ryannix123!

To run this container you need to run the OpenShift platform. You can then run the image using `oc` and `docker` commands, or alternatively, using the OpenShift web platform (https://blog.openshift.com/deploying-applications-from-images-in-openshift-part-one-web-console/).

Let me know if this helps you!

**Comment by alessfg** [comment]
If you follow the guide I posted you should not need to do anything specific to be able to run this image on OpenShift. Are you running into any specific issues?

**Comment by alessfg** [comment]
FYI I've migrated this repository to https://github.com/nginxinc/docker-nginx-unprivileged

**Comment by ryannix123** [comment]
Thanks for doing this. I can't see a way to deploy this through OpenShift.com The options in the OpenShift web UI are to deploy a Docker image. Is there a corresponding Docker instance on Docker Hub built on this spec?

**Comment by alessfg** [comment]
Indeed there is. Check https://hub.docker.com/r/nginxinc/nginx-unprivileged/tags/ to see the options available.

**Comment by alessfg** [comment]
If you have any further questions please refer to https://github.com/nginxinc/docker-nginx-unprivileged 😄
